### ISSUE TITLE
Rake issues with Redmine 3.4

### ISSUE THREAD

**Issue by mauriziotallarico** [fraoustin/redmine_closed_date#1]
Hello it seems also this plugin has issues with rake and Redmine 3.4 

> rake aborted!
Child already added
/var/www/redmine/lib/redmine/menu_manager.rb:370:in `add_at'
/var/www/redmine/lib/redmine/menu_manager.rb:387:in `add'
/var/www/redmine/lib/redmine/menu_manager.rb:305:in `push'
/var/www/redmine/plugins/redmine_dmsf/after_init.rb:7:in `block in init'
/var/www/redmine/lib/redmine/menu_manager.rb:235:in `map'
/var/www/redmine/plugins/redmine_dmsf/after_init.rb:6:in `init'
/var/www/redmine/plugins/redmine_closed_date/init.rb:23:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

Could you please check?
Thanks

**Comment by fraoustin** [comment]
Hi

Thank you for your test.
But i have a problem with issue: i can not to reproduce it

I use a docker for load redmine 3.4.

My dockerfile is

`
FROM redmine:3.4
WORKDIR /usr/src/redmine/plugins
RUN git clone https://github.com/fraoustin/redmine_closed_date.git
WORKDIR /usr/src/redmine/
`

And load with command
`
docker build -t myredmine . && docker run -d -p 3000:3000 --name myredmine myredmine
`
And i not have your problem: when a issue is closed, the date is under "Assign"

Have you more information?

**Comment by mauriziotallarico** [comment]
Hello, it could be an issue of cross-influence with another plugin: have you got DMSF installed in your docker?

**Comment by fraoustin** [comment]
i dont' know  DMSF ... do you have a github source ?

**Comment by mauriziotallarico** [comment]
Sure : https://github.com/danmunn/redmine_dmsf

**Comment by fraoustin** [comment]
Aie ... i have a error with the environnement "warning: missing REDMINE_DB_MYSQL, REDMINE_DB_POSTGRES, or REDMINE_DB_SQLSERVER environment variables" ... i use sqlite ... I look for a problem in code of dmsf

**Comment by fraoustin** [comment]
can you load rake with "--trace" please.
What is the version of dmsf that you use, please?

**Comment by mauriziotallarico** [comment]
Hi , here's my full Redmine setup:

Environment:
  Redmine version                3.4.5.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [i686-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.4
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.9
  additionals                    2.0.21
  advanced_roadmap               0.10.1
  bestest_sidebar_annihilator    1.0.0
  clipboard_image_paste          1.13
  computed_custom_field          0.0.8
  custom_menu                    1.7.0
  deployer                       0.0.1
  easy_instant_messages          2016
  export_docx                    1.2.2
  favorite_locations             0.0.1
  fedmine                        1.0.0
  global_roles                   2.1.0
  mega_calendar                  1.7.0
  pdf_export                     0.1
  progressive_projects_list      3.0.1
  project_colors                 0.0.3
  redmine__select2               1.0.5
  redmine_all_thumbnails         1.0.1
  redmine_attachment_categories  1.0.3
  redmine_attribute_quickies     1.0.2
  redmine_banner                 0.1.2
  redmine_base_deface            0.0.1
  redmine_better_overview        1.0.0
  redmine_callout_macro          1.0.0
  redmine_checklists             3.1.11
  redmine_ckeditor               1.1.5
  redmine_code_review            0.7.0
  redmine_custom_css             0.1.6
  redmine_custom_workflows       0.1.6
  redmine_dashboard              2.5.0
  redmine_default_custom_query   1.3.0
  redmine_diff_email             0.3.0
  redmine_dmsf                   1.6.1
  redmine_dynamic_file_link      0.0.1
  redmine_email_fetcher          0.3.1
  redmine_email_images           0.1.1
  redmine_extended_watchers      1.0.5
  redmine_favourite_projects     0.9
  redmine_googlesss              0.0.2
  redmine_indicator              0.2.6
  redmine_info_tab               1.1.0
  redmine_issue_badge            0.0.6
  redmine_issue_history          1.0.0
  redmine_issue_history_filter   0.0.1
  redmine_issue_icons            1.0.0
  redmine_issue_tabs             1.2.3
  redmine_issue_templates        0.2.0
  redmine_issue_to_email         1.0.1
  redmine_issue_todo_lists       1.1.1
  redmine_landing_page           0.1.1
  redmine_lightbox2              0.4.3
  redmine_list_of_roles_members  0.1.0
  redmine_mail_reminder          3.0.0.0001
  redmine_materials              0.1.7
  redmine_meeting_room_calendar  3.0.0
  redmine_more_code              1.0.0
  redmine_more_filters           1.0.2
  redmine_my_page                0.1.10
  redmine_people                 1.4.1
  redmine_per_project_formatting 0.0.4
  redmine_resource_booking_system 1.0.0
  redmine_serial_number_field    0.9.0
  redmine_silencer               0.4.1
  redmine_startpage              0.1.0
  redmine_stats                  0.0.1
  redmine_theme_changer          0.3.1
  redmine_timesheet              0.8.0
  redmine_tint_issues            1.0.2
  redmine_unc_autolink           0.0.1
  redmine_user_text_box          0.0.1
  redmine_wiki_extensions        0.8.1
  redmine_wiki_issue_fields      0.5.9
  redmine_xlsx_format_issue_exporter 0.1.3
  release_logs                   1.0.0
  rm_user_mentions               1.0.3
  that_email_log                 0.0.1
  that_issue_reply_button        0.0.1
  unread_issues                  2.2.1
  usability                      2.3.8
  view_customize                 1.1.4
  welcome_picture                1.0.0
  westaco_versions               0.0.2
  wiking                         1.1.0

**Comment by fraoustin** [comment]
Ok you have many plugins ... I think that dmsf plugin does not be a origin of your problem (I dont look for a problem in the code)
But may be a other plugin ... do you have a list a repository github for each plugin? can you test to activate one by one? (the first is the redmine_issue_closed)

**Comment by mauriziotallarico** [comment]
Hello, unfortunately it's a production environment i cannot really play with it (disabling/enabling plugins). i'll try to investigate by myself and if i have some more news i'll come back to you. if you wish you can even close the issue. thanks!

**Comment by fraoustin** [comment]
i look .. can you load on our server:
for check a presence of hook 
`
cd /usr/src/redmine
cat app/views/issues/_form.html.erb |grep view_issues_form_details_bottom
`

for check a version of file _form.html.rb
`
cd /usr/src/redmine
find ./ -name *_form.html.erb
`

thank you
